import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Dashboard
        </h1>

        <p className={styles.description}>
        Help us tailor a great surfing experience for you
        </p>

        <p className={styles.subDescription}>
        Pick which of these info you enjoy more!
        </p>

        <div className={styles.grid}>
          <Link href="/News" >
            <div className={styles.card}>
              <h2>News &rarr;</h2>
              <p>Find in-depth information about lates news</p>
            </div>
          </Link>

          <Link href="/Users">
            <div  className={styles.card}>
              <h2>Users &rarr;</h2>
              <p>Find obout the users and top users</p>
            </div>
          </Link>
        </div>
      </main>
    </div>
  )
}

export default Home
